services:
  mysql:
    image: mysql:latest
    container_name: mysql-backend
    restart: always
    env_file:
      - .env
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
